### ISSUE TITLE
Rust ring still fails to build

### ISSUE THREAD

**Issue by Milo123459** [railwayapp/nixpacks#337] opened 2022-07-20 19:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When the ring dependency is being used, it now fails to compile. 

```
#10 246.4   running "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/app/target/release/build/ring-8d77a268a77db620/out/gfp_p384.o" "crypto/fipsmodule/ec/gfp_p384.c"
#10 246.4   running "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/app/target/release/build/ring-8d77a268a77db620/out/cpu-intel.o" "crypto/cpu-intel.c"
#10 246.4   running "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "include" "-Wall" "-Wextra" "-std=c1x" "-Wbad-function-cast" "-Wnested-externs" "-Wstrict-prototypes" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/app/target/release/build/ring-8d77a268a77db620/out/poly1305_vec.o" "crypto/poly1305/poly1305_vec.c"
#10 246.4
#10 246.4
#10 246.4   error occurred: Failed to find tool. Is `ar` installed?
#10 246.4
#10 246.4
 
#10 299.3 The following warnings were emitted during compilation:
#10 299.3
#10 299.3 warning: sqlite3/sqlite3.c: In function 'sqlite3Fts5IndexQuery':
#10 299.3 warning: sqlite3/sqlite3.c:225285:18: warning: 'memcpy' specified bound 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
#10 299.3 warning: 225285 |     if( nToken ) memcpy(&buf.p[1], pToken, nToken);
#10 299.3 warning:        |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#10 299.3
#10 299.3 error: failed to run custom build command for `libsqlite3-sys v0.22.2`
#10 299.3
#10 299.3 Caused by:
#10 299.3   process didn't exit successfully: `/app/target/release/build/libsqlite3-sys-ebf66ecf8271228a/build-script-build` (exit status: 1)
```

Also happens with `libsqllite3-sys`. Seems like it wants `ar`, but I'm not sure what that is.

cc @coffee-cup 

### To reproduce

1. Have a rust crate with the `ring` dependency.

### Expected behavior

It shouldn't spaz out

### Environment

railway

**Comment by coffee-cup** [comment] 2022-07-20 20:14
Duplicate of https://github.com/railwayapp/nixpacks/issues/258

**Closed by coffee-cup** 2022-07-20 20:14 UTC
Labels: bug

**Comment by Milo123459** [comment] 2022-07-20 20:17
Oh right, saw that issue but thought that one was platform specific.
