### ISSUE TITLE
NodeJS runtime error

### ISSUE THREAD

**Issue by mrhappyma** [railwayapp/nixpacks#386] opened 2022-08-06 21:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[(originally asked in the Railway discord server)](https://discord.com/channels/713503345364697088/713503345867882498/1005581506732896271)

I’m getting some weird errors when starting my app, only started when I switched to nixpacks.
```
1: 0xa673d8 node::Abort() [node]
2: 0xa67467  [node]
3: 0xae9422 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
4: 0xae9552 node::NodePlatform::NodePlatform(int, v8::TracingController*) [node]
5: 0xa271bf node::V8Platform::Initialize(int) [node]
6: 0xa254db node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [node]
7: 0xa25669 node::InitializeOncePerProcess(int, char**) [node]
8: 0xa256c8 node::Start(int, char**) [node]
9: 0x7f2b5d602237  [/nix/store/k56d9sk88pvrqhvwpa6msdf8gpwnimf6-glibc-2.34-210/lib/libc.so.6]
10: 0x7f2b5d6022f5 __libc_start_main [/nix/store/k56d9sk88pvrqhvwpa6msdf8gpwnimf6-glibc-2.34-210/lib/libc.so.6]
11: 0x98be71 _start [node]
```

### Environment

Node.js project on Railway. Wasn’t quite sure what information would be helpful so there’s not much here, but I’d be open to provide more information as requested.

**Comment by Milo123459** [comment] 2022-08-07 07:55
Could you share your package.json? I believe this is an issue with express, so could you try deploying a blank express server?

**Comment by mrhappyma** [comment] 2022-08-07 13:20
> Could you share your package.json? I believe this is an issue with express, so could you try deploying a blank express server?

My project is a Discord bot...
Here is my package.json - https://gist.github.com/mrhappyma/fd23718462b918fb0914cff7b2d4b99b

**Comment by coffee-cup** [comment] 2022-08-08 18:13
Are you sure this is an error with Nixpacks? After the image is created Nixpacks is not involved in the process anymore. To me this seems like a NodeJS error or bug with another part of the Railway platform.

**Comment by Milo123459** [comment] 2022-08-08 18:21
I've seen multiple people report that this issue only happens after switching to nixpacks. Though, that could be some versioning bug.

**Comment by coffee-cup** [comment] 2022-08-08 21:40
Is there a minimal reproducible example where this consistently happens? If it isn't 100% reproducible then I expect it is an issue with the runtime/how the container is deployed. Nixpacks might be a red herring because users see this issue shortly after switching to Nixpacks but there is another Railway bug that is causing the crash.

**Comment by mrhappyma** [comment] 2022-08-10 16:36
All I know is that deploys fail with that error, only when I am using nixpacks 🤷‍♂️

**Comment by Milo123459** [comment] 2022-08-10 16:52
> Is there a minimal reproducible example where this consistently happens? If it isn't 100% reproducible then I expect it is an issue with the runtime/how the container is deployed. Nixpacks might be a red herring because users see this issue shortly after switching to Nixpacks but there is another Railway bug that is causing the crash.
> 
> 
> 
> I know I have run ExpressJS many times with Nixpacks with no issues. So unless there is an MRE I will close this issue.

I think it could be the arch/os/platform the image is running on. They might be built for one and fail for the other.

**Comment by coffee-cup** [comment] 2022-08-11 23:35
After some digging in, this seems to be an issue running Node 16 on some Railway hosts. The team is working on a fix but I will close this issue since it is not a Nixpacks problem.

**Closed by coffee-cup** 2022-08-11 23:35 UTC
Labels: bug
