### ISSUE TITLE
Ignore files in .gitignore & show a warning when calling includes_file 

### ISSUE THREAD

**Issue by AhmedMozaly** [railwayapp/nixpacks#563] opened 2022-09-19 11:11 UTC
### Feature request
If there is already a `package-lock.json` file in the codebase, And user added `package-lock.json` to `.gitignore` by mistake 
Running `npm ci` in this case will fail

It's better to detect such case up front. Raise a clear error about, With a suggestion on how to fix
For reference: https://github.com/railwayapp/nixpacks/blob/main/src/providers/node/mod.rs#L270

**Comment by nebulatgs** [comment] 2022-09-19 11:27
if no lockfile is detected, we don’t have to fail the build, instead we can display a warning and fall back to a normal non-locked installation

**Comment by AhmedMozaly** [comment] 2022-09-19 11:46
> if no lockfile is detected, we don’t have to fail the build, instead we can display a warning and fall back to a normal non-locked installation

Would be a nice option as well!

**Comment by AhmedMozaly** [comment] 2022-09-19 12:17
Will we be able to warn the user if a certain file may have been added to `. gitignore ` by mistake? (like the issue we're discussing here)

**Comment by Milo123459** [comment] 2022-09-19 12:19
I think that is out of scope to be completely honest. If a file is gitignored, we can't get access to it, thus we should just set it to `false` if the file exists and is gitignored.

However, we could make the function print a warning saying "file was found locally but is in gitignore, ignoring" or something like that. We shouldn't specialise this just to one file though, and it should be implemented into the function.

**Comment by AhmedMozaly** [comment] 2022-09-19 14:24
Yeah, that would achieve the same result but will cover any future cases as well (other than `package-lock.json`)

**Comment by coffee-cup** [comment] 2022-09-19 14:36
If the app `includes_files` read from the app that was copied into `/tmp` then it wouldn't be an issue anymore because ignored files are not copied. The problem is that currently the app reads from the original source but all those files might not get copied into the container.

**Comment by AhmedMozaly** [comment] 2022-09-19 15:18
For the record, Nixpacks has two modes
* When `--current-dir` is passed, no files will be copied and all the files in code repo will be available to Nixpacks build command

* When `--current-dir` is NOT passed, a temp direcotry will be created > files will be copied from cloned code (respecting `.gitignore`) > only files copied will be available to Nixpacks build command

After discussion, it would be better for Nixpacks  to keep this responsibility at the user side (speaking about deciding which files are available during the build), if some files are not needed. User can remove

**Comment by exPHAT** [comment] 2022-09-21 02:03
@AhmedMozaly is there any way to replicate the `--current-dir` functionality on railway or via the nixpack config file? There are files in our `.gitignore` we rely on, but are being excluded due to this functionality.

**Comment by AhmedMozaly** [comment] 2022-09-21 02:33
You can pass `--current-dir` to Nixpacks and it won't copy your codebase to any where else
It will instead process all your files from the same target directory you specified

For example `nixpacks build ./my-codebase --current-dir`

Should make all the files under `./my-codebase` available to Nixpacks
The only thing to notice, is that Nixpacks will create a `.nixpacks` directory under `./my-codebase` (to write its output files to)

if `./my-codebase` is a git repo, be aware that you may push `.nixpacks` directory by mistake

**Comment by AhmedMozaly** [comment] 2022-09-21 02:36
> is there any way to replicate the `--current-dir` functionality on railway

Oh, just noticed you are referring to Railway build. We already planning to issue a fix this week!
Will keep you updated

**Closed** 2022-09-21 09:33 UTC
Labels: enhancement

**Comment by AhmedMozaly** [comment] 2022-09-22 17:57
@exPHAT It should be fixed now on Railway, kindly confirm!

**Comment by exPHAT** [comment] 2022-09-22 18:42
> @exPHAT It should be fixed now on Railway, kindly confirm!


Working now! Thank you!
