### ISSUE TITLE
Ruby rails build failure

### ISSUE THREAD

**Issue by cabello** [railwayapp/nixpacks#700] opened 2022-12-03 14:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I tried to build a Ruby app:

```
❯ nixpacks build app --name app-nix --verbose

╔══════════════════════════════ Nixpacks v0.15.0 ══════════════════════════════╗
║ setup      │ pkgs: imagemagick, procps, libpq-dev, libmagickwand-dev         ║
║            │ cmds: curl -sSL https://get.rvm.io | bash -s stable && .        ║
║            │ /etc/profile.d/rvm.sh && rvm install 3.1.2 && rvm --default use ║
║            │ 3.1.2 && gem install bundler:2.3.23 && rm -rf                   ║
║            │ /usr/local/rvm/src                                              ║
║            │ echo 'source /usr/local/rvm/scripts/rvm' >> /root/.profile      ║
║──────────────────────────────────────────────────────────────────────────────║
║ install    │ bundle install                                                  ║
║──────────────────────────────────────────────────────────────────────────────║
║ build      │ bundle exec rake assets:precompile                              ║
║──────────────────────────────────────────────────────────────────────────────║
║ start      │ bundle exec puma                                                ║
╚══════════════════════════════════════════════════════════════════════════════╝

Error: Writing app

Caused by:
    Permission denied (os error 13)
```

If I use `sudo`, it starts building but fails:

```
 > [internal] load metadata for ghcr.io/railwayapp/nixpacks:debian-1669098887:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: ``
Error: Docker build failed
```

### To reproduce

On an Apple M1 try to build a Ruby app.

### Expected behavior

The app to build and be runnable.

### Environment

nixpacks 0.15.0
Ventura 13.0.1
Apple Silicon

**Comment by coffee-cup** [comment] 2022-12-14 21:23
This looks like a Docker issue on your machine. Can you please provide a repo to reproduce this issue on. Closing for now, but will reopen if it is a Nixpacks issue.

**Closed by coffee-cup** 2022-12-14 21:23 UTC
Labels: bug

**Comment by emilbryggare** [comment] 2022-12-15 11:52
I stumbled on this error today as well for a Remix app using a fresh install of Nixpacks. I was able to resolve it by pulling the docker image manually using docker and rerunning the command.

```
docker pull ghcr.io/railwayapp/nixpacks:debian-1670285109
sudo nixpacks build . --name tabello-app
```

**Environment**
nixpacks 0.16.0
Ventura 13.0.1
Apple Silicon M1

**Comment by frontsideair** [comment] 2023-01-04 09:47
I'm having the same issue and resolved it the same way. To be more precise;

- Getting this error without sudo: `Error: Writing app Caused by: Permission denied (os error 13)`
- Unable to pull with sudo
- Manually running `docker pull`
- It now works with sudo (but not without sudo)

I'm under the impression that it should work without sudo.

**Environment**
nixpacks 1.0.3
Apple Silicon M2
Ventura 13.0.1
Docker Desktop 4.14.1

**Comment by henrikbjorn** [comment] 2023-03-01 11:38
For a newer Rails project I am not seeing this

But for an older ruby 2.6 I am seeing this and running as sudo is not really a fix. Is there a way to debug this? `--verbose` isn't given any more information than permission denied.

I am on a M1 chip.

cc @coffee-cup

**Comment by henrikbjorn** [comment] 2023-03-03 09:51
@frontsideair 

I figured it out. In our Rails application locally we are mounting something shared in the container for development. These a .bash_history or .viminfo

They are created with low file permissions 

```
-rw-------  1 Henrik  staff   5718 Sep 29 15:44 .viminfo
```

After removing those files I am able to build our rails application without any issues.

@coffee-cup Would it be an idea to have something like `.nixpacksignore` or something?

**Comment by baptisteArno** [comment] 2024-01-31 14:08
> In my case, deleting all untracked files with `git clean -fdx` solved the issue. Most likely the problem was `node_modules`, which I installed with `pnpm` and linked from a global cache.

This!!! Thank you 🙏

**Comment by acaloiaro** [comment] 2024-02-22 01:31
This problem can manifest in a multitude of ways, as is obvious by reading other users' experiences here.

Excuse my lack of nixpacks-specific knowledge here; I may use some terminology incorrectly. 
 
For Go projects, this _can_ be a file permission issue. To be even more specific, for Go projects using `devenv`, your go modules are added to `.devenv/state/go/pkg`. When `nixpacks` copies this directory into its temporary directory during `nixpacks build ...`, it copies the contents of `.devenv/state/go/pkg` with existing file permissions. These permissions are `444` for regular files, which is read-only, even by the owning user. 

During most build processes, read-only dependencies are fine, but nixpacks opens files with `O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC`. Which means Go dependencies must be _writable_ by the user running `nixpacks build ...`. 

My solution was:

`chmod 600 .denvenv/state/go/pkg`

**Comment by iloveitaly** [comment] 2024-08-02 18:47
It would be great if it was easy to understand _which_ file is causing this error. Right now it's not possible, especially on macos which doesn't have `strace` and friends.
