### ISSUE TITLE
Ruby caching still not working

### ISSUE THREAD

**Issue by flybayer** [railwayapp/nixpacks#641] opened 2022-10-30 21:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Ruby install is still not being cached correctly, originally reported in https://github.com/railwayapp/nixpacks/issues/624

I'm seeing two problems:

### 1. Locally, intermediately `COPY . /app/` is being executed before rvm install.

Using https://github.com/bullet-train-co/bullet_train repo, running `nixpacks build .` repeatedly results in randomly different order of `COPY ./app/` and rvm install.

**Install before file copy** 

```
 => [stage-0  1/19] FROM ghcr.io/railwayapp/nixpacks:debian-1666656625@sha256:07f8d22eb2a00effe17fc6304  0.0s
 => CACHED [stage-0  2/19] WORKDIR /app/                                                                 0.0s
 => CACHED [stage-0  3/19] COPY .nixpacks/nixpkgs-a0b7e70db7a55088d3de0cc370a59f9fbcc906c3.nix .nixpack  0.0s
 => CACHED [stage-0  4/19] RUN nix-env -if .nixpacks/nixpkgs-a0b7e70db7a55088d3de0cc370a59f9fbcc906c3.n  0.0s
 => CACHED [stage-0  5/19] RUN apt-get update && apt-get install -y --no-install-recommends procps libp  0.0s
 => CACHED [stage-0  6/19] RUN  curl -sSL https://get.rvm.io | bash -s stable && . /etc/profile.d/rvm.s  0.0s
 => CACHED [stage-0  7/19] RUN  rvm install 3.1.2                                                        0.0s
 => CACHED [stage-0  8/19] RUN  rvm --default use 3.1.2                                                  0.0s
 => CACHED [stage-0  9/19] RUN  gem install bundler:2.3.8                                                0.0s
 => CACHED [stage-0 10/19] RUN  echo 'source /usr/local/rvm/scripts/rvm' >> /root/.profile               0.0s
 => CACHED [stage-0 11/19] COPY . /app/                                                                  0.0s
 => CACHED [stage-0 12/19] RUN printf '\nPATH=/usr/local/rvm/rubies/3.1.2/bin:/usr/local/rvm/gems/3.1.2  0.0s
 => CACHED [stage-0 13/19] COPY . /app/                                                                  0.0s
 => CANCELED [stage-0 14/19] RUN --mount=type=cache,id=muk66F5hTK4-/root/bundle/cache,target=/root/.bun  1.1s
```

**File copy before install**

```
 => [stage-0  1/19] FROM ghcr.io/railwayapp/nixpacks:debian-1666656625@sha256:07f8d22eb2a00effe17fc6304  0.0s
 => [internal] load build context                                                                        0.2s
 => => transferring context: 3.74MB                                                                      0.1s
 => CACHED [stage-0  2/19] WORKDIR /app/                                                                 0.0s
 => CACHED [stage-0  3/19] COPY .nixpacks/nixpkgs-a0b7e70db7a55088d3de0cc370a59f9fbcc906c3.nix .nixpack  0.0s
 => CACHED [stage-0  4/19] RUN nix-env -if .nixpacks/nixpkgs-a0b7e70db7a55088d3de0cc370a59f9fbcc906c3.n  0.0s
 => CACHED [stage-0  5/19] RUN apt-get update && apt-get install -y --no-install-recommends procps libp  0.0s
 => [stage-0  6/19] COPY . /app/                                                                         0.1s
 => CANCELED [stage-0  7/19] RUN  curl -sSL https://get.rvm.io | bash -s stable && . /etc/profile.d/rvm  2.6s
```

### 2. In production, rvm install is always before files are copied but it's never cached.

```
8:03:14 PM: #7 [internal] load build context
8:03:14 PM: #7 sha*56:1eb9a8*bacd3f8d*660bfb868156abadc79175*3cafd8*63c14e65feb967*7a1
8:03:14 PM: #7 transferring context: 9.69MB 0.*s done
8:03:14 PM: #7 DONE 0.*s
8:03:14 PM: 
8:03:14 PM: #6 [stage-0  2/20] WORKDIR /app/
8:03:14 PM: #6 sha*56:7177063938fcb83ad1c0696**7c06c*e8c870b94*57cc94fae0f5*d8c5b*fa65
8:03:14 PM: #6 CACHED
8:03:14 PM: 
8:03:14 PM: #8 [stage-0  3/20] COPY .nixpacks/nixpkgs-a0b7e70db7a55088d3de0cc370a59f9fbcc906c3.nix .nixpacks/nixpkgs-a0b7e70db7a55088d3de0cc370a59f9fbcc906c3.nix
8:03:14 PM: #8 sha*56:c8aa349d619**076ebc6f0c*b906dafa3b108de76dfdf354d3904735a807677*
8:03:14 PM: #8 CACHED
8:03:14 PM: 
8:03:14 PM: #9 [stage-0  4/20] RUN nix-env -if .nixpacks/nixpkgs-a0b7e70db7a55088d3de0cc370a59f9fbcc906c3.nix && nix-collect-garbage -d
8:03:14 PM: #9 sha*56:f90d4b0*f843935a6*e06ae8*fc3f9b34ff67b836171f44b74570be19d*9*469
8:03:14 PM: #9 CACHED
8:03:14 PM: 
8:03:14 PM: #10 [stage-0  5/20] RUN apt-get update && apt-get install -y --no-install-recommends *** procps libpq-dev ***
8:03:14 PM: #10 sha*56:8480d5357788e8bc9ffc6f1be1686bab50f*ef*fef964f63d*9600a4f*193a97
8:03:14 PM: #10 CACHED
8:03:14 PM: 
8:03:14 PM: #11 [stage-0  6/20] RUN  curl -sSL https://get.rvm.io | bash -s stable && . /etc/profile.d/rvm.sh
8:03:14 PM: #11 sha*56:fb0581ac6f170c4*a393e7bbe00490d81cb8b896fa86078dd6e55c0edabb7813
8:03:16 PM: #11 0.819 curl: (**) The requested URL returned error: 403 
8:03:16 PM: #11 0.8*0 WARN: ...the preceeding error with code ** occurred while fetching https://api.github.com/repos/rvm/rvm/tags
8:03:16 PM: #11 1.5*4 Downloading https://github.com/rvm/rvm/archive/1.*9.1*.tar.gz
8:03:16 PM: #11 1.734 Downloading https://github.com/rvm/rvm/releases/download/1.*9.1*/1.*9.1*.tar.gz.asc
8:03:16 PM: #11 1.953 Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.*9.1*/1.*9.1*.tar.gz.asc',
8:03:16 PM: #11 1.953 but no GPG software exists to validate it, skipping.
8:03:16 PM: #11 *.033 Creating group 'rvm'
8:03:16 PM: #11 *.050 Installing RVM to /usr/local/rvm/
8:03:18 PM: #11 3.5*6 Installation of RVM in /usr/local/rvm/ is almost complete:
8:03:18 PM: #11 3.5*6 
8:03:18 PM: #11 3.5*6   * First you need to add all users that will be using rvm to 'rvm' group,
8:03:18 PM: #11 3.5*6     and logout - login again, anyone using rvm will be operating with `umask u=rwx,g=rwx,o=rx`.
8:03:18 PM: #11 3.5*6 
8:03:18 PM: #11 3.5*6   * To start using RVM you need to run `source /etc/profile.d/rvm.sh`
8:03:18 PM: #11 3.5*6     in all your open shell windows, in rare cases you need to reopen all shell windows.
8:03:18 PM: #11 3.568   * Please do NOT forget to add your users to the <code>rvm</code> group.
8:03:18 PM: #11 3.568      The installer no longer auto-adds root or users to the rvm group. Admins must do this.
8:03:18 PM: #11 3.568      Also, please note that group memberships are ONLY evaluated at login time.
8:03:18 PM: #11 3.568      This means that users must log out then back in before group membership takes effect!
8:03:18 PM: #11 3.580 <warn>Thanks for installing RVM 🙏</warn>
8:03:18 PM: #11 3.580 Please consider donating to our open collective to help us maintain RVM.
8:03:18 PM: #11 3.580 
8:03:18 PM: #11 3.580 👉  Donate: <code>https://opencollective.com/rvm/donate</code>
8:03:18 PM: #11 3.580 
8:03:18 PM: #11 3.580 
8:03:20 PM: #11 DONE 5.5s
8:03:20 PM: 
8:03:20 PM: #1* [stage-0  7/20] RUN  rvm install 3.0.3
8:03:20 PM: #1* sha*56:ee69f16fbb84f8*3764b195ce3953*e99ad0bebbd9118dc84b0f904837f1*518
8:03:20 PM: #1* 0.57* Warning! PATH is not properly set up, /usr/local/rvm/gems/3.0.3/bin is not available.
8:03:20 PM: #1* 0.57*          <log>Usually this is caused by shell initialization files. Search for <code>PATH=...</code> entries.
8:03:20 PM: #1* 0.57*          You can also re-add RVM to your profile by running: <code>rvm get stable --auto-dotfiles</code>
8:03:20 PM: #1* 0.57*          To fix it temporarily in this shell session run: <code>rvm use 3.0.3</code>
8:03:20 PM: #1* 0.57*          To ignore this error add <code>rvm_silence_path_mismatch_check_flag=1</code> to your <code>~/.rvmrc</code> file.
8:03:22 PM: #1* 0.885 Searching for binary rubies, this might take some time.
8:03:24 PM: #1* 3.716 No binary rubies available for: debian/11/x86_64/ruby-3.0.3.
8:03:24 PM: #1* 3.716 Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
8:03:24 PM: #1* 3.7*4 Checking requirements for debian.
8:03:24 PM: #1* 4.055 Installing requirements for debian.
8:03:26 PM: #1* 4.070 Updating system..
8:03:32 PM: #1* 4.780 Installing required packages: patch, bzip*, gawk, g++, gcc, bison, libgdbm-dev, libncurses5-dev, libsqlite3-dev, libtool, libyaml-dev, patch, sqlite3, libgmp-dev, libreadline-dev, libssl-dev...........................
8:03:32 PM: #1* 1*.44 Requirements installation successful.
8:03:32 PM: #1* 1*.5* Installing Ruby from source to: /usr/local/rvm/rubies/ruby-3.0.3, this may take a while depending on your cpu(s)...
8:03:32 PM: #1* 1*.58 ruby-3.0.3 - #downloading ruby-3.0.3, this may take a while depending on your connection...
8:03:32 PM: #1* 1*.66   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
8:03:32 PM: #1* 1*.66                                  Dload  Upload   Total   Spent    Left  Speed
8:03:34 PM: 100 19.3M  100 19.3M    0     0  31.4M      0 --:--:-- --:--:-- --:--:-- 31.3M
8:03:34 PM: #1* 13.*7 No checksum for downloaded archive, recording checksum in user configuration.
8:03:34 PM: #1* 13.38 ruby-3.0.3 - #extracting ruby-3.0.3 to /usr/local/rvm/src/ruby-3.0.3.....
8:03:56 PM: #1* 14.1* ruby-3.0.3 - #configuring.........................................................................
8:03:56 PM: #1* 36.63 ruby-3.0.3 - #post-configuration..
8:05:36 PM: #1* 36.64 ruby-3.0.3 - #compiling............................................................................................
8:05:40 PM: #1* 136.5 ruby-3.0.3 - #installing.....................
8:05:40 PM: #1* 139.5 ruby-3.0.3 - #making binaries executable...
8:05:40 PM: #1* 139.8 Installed rubygems 3.*.3* is newer than 3.0.9 provided with installed ruby, skipping installation, use --force to force installation.
8:05:40 PM: #1* 139.8 ruby-3.0.3 - #gemset created /usr/local/rvm/gems/ruby-3.0.3@global
8:05:42 PM: #1* 139.8 ruby-3.0.3 - #importing gemset /usr/local/rvm/gemsets/global.gems..........................................................
8:05:42 PM: #1* 141.6 ruby-3.0.3 - #generating global wrappers........
8:05:42 PM: #1* 14*.0 ruby-3.0.3 - #gemset created /usr/local/rvm/gems/ruby-3.0.3
8:05:42 PM: #1* 14*.1 ruby-3.0.3 - #importing gemsetfile /usr/local/rvm/gemsets/default.gems evaluated to empty gem list
8:05:42 PM: #1* 14*.1 ruby-3.0.3 - #generating default wrappers........
8:05:42 PM: #1* 14*.6 ruby-3.0.3 - #adjusting #shebangs for (gem irb erb ri rdoc ***rb rake).
8:05:42 PM: #1* 14*.6 Install of ruby-3.0.3 - #complete 
8:05:42 PM: #1* 14*.7 Ruby was built without documentation, to build it run: rvm docs generate-ri
8:05:44 PM: #1* DONE 143.4s
```

### Environment

nixpacks 0.11.3

**Comment by coffee-cup** [comment] 2022-10-31 19:19
I think I see what the issue is. With the bullet_train repo both Ruby and Node get installed. There seems to be some inconsistency with the order that these phases run in which is invalidating the Docker layer cache. I'm just taking a look at making the order deterministic now.

**Comment by coffee-cup** [comment] 2022-10-31 19:56
This should fix the layer caching issue when installing Ruby when Node is also included. https://github.com/railwayapp/nixpacks/pull/644

There were two problems
1. The dockerfile content for the phases was not in a deterministic order. This was only a problem when multiple providers were running. (In this case the ruby:setup and node:setup phases would flip back and forth and invalidate the Docker layer cache between runs)
2. The node setup phase was just outputting `COPY . /app` and nothing else. This would invalidate the layer cache for any further phases. Fixed by simplifying nooping in that case.

As for this PR, https://github.com/railwayapp/nixpacks/pull/642. It does break a few Ruby apps that we have seen on Railway so will need to check that the `Gemfile` does not use any local apps by default. That should be as simple as checking that `gem "local"` is not present in the `Gemfile` (example: https://github.com/railwayapp/nixpacks/blob/main/examples/ruby-local-deps/Gemfile#L3).

**Closed** 2022-11-01 15:04 UTC
Labels: bug
