### ISSUE TITLE
Ruby: bundle not in path

### ISSUE THREAD

**Issue by JakeCooper** [railwayapp/nixpacks#461] opened 2022-08-28 21:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The current Ruby provider has a bug where bundle is not in the path

Related Thread: [here](https://discord.com/channels/713503345364697088/1013074738509250691/1013074738509250691)

Workaround: Set the NIXPACKS_START_COMMAND variable manually and it will work

Need a repo example but cataloging the issue here

### Environment

n/a

**Comment by coffee-cup** [comment] 2022-08-28 21:29
I believe the issue is more with how Railway starts the containers. bundle is in the PATH but only if .profile is loaded. By default when starting the container it is. But the way Railway starts containers with a custom start command means that the PATH isn’t loaded correctly.

**Comment by coffee-cup** [comment] 2022-09-01 18:24
This is fixed in the latest version (0.4.0)

**Closed by coffee-cup** 2022-09-01 18:24 UTC
Labels: bug

**Comment by KrauseFx** [comment] 2022-09-01 18:33
Beautiful, thank you
